### ISSUE TITLE
Choose an appropriate license for R

### ISSUE THREAD

**Issue by DanielCairns** [UBC-MDS/nameformeR#32]
Discuss whether we should use a different license (in this issue).

(Also link an equivalent issue in the Python repo to this issue)

**Comment by ZilongYi** [comment]
![image](https://user-images.githubusercontent.com/73105919/215845462-244f5cd5-99f0-4606-9cbb-e6d04c070d45.png)
Is this expected?

**Comment by eyrexh** [comment]
Similar issue discussed in Python: https://github.com/UBC-MDS/nameforme/issues/93

**Comment by BruceUBC** [comment]
I think the MIT license is good though. It is short and easy to understand, making it more accessible for users and developers.
Our packages is not that complex and used for private use. A license with no restrictions on patent use will be suitable here. Therefore, the MIT license could be a good choice of freedom and flexibility.

**Comment by eyrexh** [comment]
Considering we are developing a package based on open-source data and we are happy to welcome our MDS community to contribute. We might think about using the [Apache License 2.0](https://choosealicense.com/licenses/apache-2.0/). However, I agreed with Bruce that MIT is simple and robust. It can also be used in community contribution. Like, [npm packages](https://libraries.io/search?platforms=npm) is using the [MIT](https://choosealicense.com/licenses/mit/) as a group contributed community.

**Comment by DanielCairns** [comment]
Agreed, MIT is the best license choice.

Our package is mostly silly (it won't have that many strong real world applications), and is also mostly just fairly simple mutations to an existing public data source. This is to say: there's not much we need to protect, and also not a huge demand for our packages that others might choose to build upon. Let's keep it open and easy to use and maintain.

Plus, we've already set up both packages using the MIT license, so we would need to see a tangible upgrade to bother making the switch.

**Comment by ZilongYi** [comment]
Agreed,  considering MIT is the most commonly used license, which makes people know immediately how they can use/distribute/modify with our package. 
Also, I don't see any point where we might not want people to use our package. So, as long as it is simple and widely used, it should be good enough for our purpose.
